-- Fleet, trip, telemetry, fuel, maintenance, performance, and route domains.

create type public.vehicle_status as enum (
  'active',
  'maintenance',
  'offline'
);

create type public.driver_status as enum (
  'available',
  'on_trip',
  'offline'
);

create type public.trip_status as enum (
  'scheduled',
  'active',
  'completed',
  'cancelled'
);

create type public.maintenance_status as enum (
  'scheduled',
  'in_progress',
  'completed'
);

create table public.vehicles (
  id bigint generated by default as identity primary key,
  license_plate text not null unique,
  model text not null,
  make text not null,
  year integer not null,
  type text not null default 'Sedan',
  status public.vehicle_status not null default 'active',
  fuel_capacity numeric(8, 2) not null,
  current_gps_lat numeric(10, 8),
  current_gps_lng numeric(11, 8),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.drivers (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  license_number text not null unique,
  status public.driver_status not null default 'available',
  performance_score numeric(5, 2) not null default 100.00,
  total_trips integer not null default 0,
  total_distance_km numeric(10, 2) not null default 0.00,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index drivers_user_id_index on public.drivers (user_id);

create table public.trips (
  id bigint generated by default as identity primary key,
  booking_reference_id text,
  driver_id bigint references public.drivers (id) on delete set null,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  start_location text not null,
  end_location text not null,
  start_lat numeric(10, 8) not null,
  start_lng numeric(11, 8) not null,
  end_lat numeric(10, 8) not null,
  end_lng numeric(11, 8) not null,
  status public.trip_status not null default 'scheduled',
  distance_km numeric(8, 2) not null,
  estimated_duration_minutes integer not null,
  actual_duration_minutes integer,
  estimated_fuel_liters numeric(8, 2),
  actual_fuel_liters numeric(8, 2),
  start_time timestamptz,
  end_time timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index trips_driver_status_index on public.trips (driver_id, status);
create index trips_vehicle_status_index on public.trips (vehicle_id, status);

create table public.trip_logs (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips (id) on delete cascade,
  lat numeric(10, 8) not null,
  lng numeric(11, 8) not null,
  speed_kmh numeric(5, 2) not null,
  idle_time_seconds integer not null default 0,
  timestamp timestamptz not null default now()
);

create index trip_logs_trip_id_index on public.trip_logs (trip_id);

create table public.fuel_logs (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles (id) on delete cascade,
  trip_id bigint references public.trips (id) on delete set null,
  date date not null,
  amount_liters numeric(8, 2) not null,
  cost numeric(10, 2) not null,
  odometer_reading numeric(10, 2) not null,
  fuel_type text not null default 'DC Fast Charge (kWh)',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index fuel_logs_vehicle_date_index on public.fuel_logs (vehicle_id, date);
create index fuel_logs_trip_id_index on public.fuel_logs (trip_id);

create table public.maintenance_records (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles (id) on delete cascade,
  service_type text not null,
  description text,
  cost numeric(10, 2) not null,
  status public.maintenance_status not null default 'scheduled',
  scheduled_date date not null,
  completion_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index maintenance_records_vehicle_status_index on public.maintenance_records (vehicle_id, status);

create table public.performance_records (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers (id) on delete cascade,
  trip_id bigint not null references public.trips (id) on delete cascade,
  speeding_events integer not null default 0,
  harsh_braking_events integer not null default 0,
  idle_minutes numeric(5, 2) not null default 0.00,
  safety_score integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index performance_records_driver_id_index on public.performance_records (driver_id);
create index performance_records_trip_id_index on public.performance_records (trip_id);

create table public.routes (
  id bigint generated by default as identity primary key,
  start_point text not null,
  end_point text not null,
  distance_km numeric(8, 2) not null,
  optimized_path jsonb not null,
  avg_fuel_consumption numeric(8, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
