-- Security and authentication audit events.
-- No Supabase Auth foreign key or RLS policy is defined: the Laravel application
-- authenticates against public.users and authorizes through server-side sessions.

create table public.security_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  email text,
  ip_address varchar(45),
  user_agent text,
  details text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index security_logs_created_at_index on public.security_logs (created_at);
create index security_logs_email_index on public.security_logs (email);
