-- Vehicle Reservation and Dispatch System (VRDS).

create type public.reservation_status as enum (
  'pending',
  'approved',
  'rejected',
  'completed',
  'cancelled'
);

create table public.vehicle_reservations (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles (id) on delete cascade,
  driver_id bigint references public.drivers (id) on delete set null,
  requested_by bigint not null references public.users (id) on delete cascade,
  purpose text not null,
  reservation_date date not null,
  start_time time not null,
  end_time time not null,
  status public.reservation_status not null default 'pending',
  remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index vehicle_reservations_date_status_index
  on public.vehicle_reservations (reservation_date, status);
create index vehicle_reservations_vehicle_date_index
  on public.vehicle_reservations (vehicle_id, reservation_date);
