-- Core application identity and Laravel-compatible infrastructure.
-- This application authenticates against public.users and does not use Supabase Auth.

create type public.user_role as enum (
  'admin',
  'fleet_manager',
  'dispatcher',
  'finance',
  'operations',
  'driver'
);

create table public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  email_verified_at timestamptz,
  password text not null,
  role public.user_role not null default 'dispatcher',
  phone_number text,
  avatar_path text,
  job_title text,
  last_otp_verified_at timestamptz,
  remember_token varchar(100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.password_reset_tokens (
  email text primary key,
  token text not null,
  created_at timestamptz
);

create table public.sessions (
  id varchar(255) primary key,
  user_id bigint,
  ip_address varchar(45),
  user_agent text,
  payload text not null,
  last_activity integer not null
);

create index sessions_user_id_index on public.sessions (user_id);
create index sessions_last_activity_index on public.sessions (last_activity);

create table public.cache (
  key varchar(255) primary key,
  value text not null,
  expiration integer not null
);

create index cache_expiration_index on public.cache (expiration);

create table public.cache_locks (
  key varchar(255) primary key,
  owner varchar(255) not null,
  expiration integer not null
);

create index cache_locks_expiration_index on public.cache_locks (expiration);

create table public.jobs (
  id bigint generated by default as identity primary key,
  queue varchar(255) not null,
  payload text not null,
  attempts smallint not null,
  reserved_at integer,
  available_at integer not null,
  created_at integer not null
);

create index jobs_queue_index on public.jobs (queue);

create table public.job_batches (
  id varchar(255) primary key,
  name varchar(255) not null,
  total_jobs integer not null,
  pending_jobs integer not null,
  failed_jobs integer not null,
  failed_job_ids text not null,
  options text,
  cancelled_at integer,
  created_at integer not null,
  finished_at integer
);

create table public.failed_jobs (
  id bigint generated by default as identity primary key,
  uuid varchar(255) not null unique,
  connection text not null,
  queue text not null,
  payload text not null,
  exception text not null,
  failed_at timestamptz not null default now()
);
